baseurl = "http://truonix.netlify.com/"
languageCode = "en-us"
title = "Truonix"
theme = "osprey"
tags = ["appsec", "security", "governance"]
canonifyURLS = true
googleAnalytics = ""
disqusShortname = "yanfosec"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
    tagline = "Future Home of Truonix..."
    author = "Yan Kravchenko"
    description = "Redefining Partnership in Information and Application Security."
    logoBig = "/images/truonix-logo.png"
    logoSmall = "/images/truonix-logo.png"
    favicon = "favicon.ico"
    opengraphImage = "/images/truonix-logo.png"
    twitter = "truonix"
    linkedin = "truonix"
    github = "yanfosec"
    email = "ykravchenko@luriellp.com"
    googleTagManager = ""
    highlightJS = true
    copyright = true
    credit = false
    customCSS = false
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = false
    staticForm = true

[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 1

[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 2

